### ISSUE TITLE
usb camera via docker ?

### ISSUE THREAD

**Issue by abate** [kerberos-io/machinery#105]
I'm trying to pass to machinery all it needs to access my usb cam on my host.
This is my modified docker.compose.yml

```
machinery:
    image: kerberos/machinery
    ports:
    - "8889"
    privileged: true
    volumes:
    - "/dev/bus/usb:/dev/bus/usb"
    devices:
    - "/dev/video0:/dev/video0"
```
I'm sure I'm missing something. How can I make it work ?
